"""empty message

Revision ID: a274fc08a865
Revises: 1f8265c8ebbc
Create Date: 2021-01-16 15:21:40.273478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a274fc08a865'
down_revision = '1f8265c8ebbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('actor_id', sa.Integer(), nullable=True))
    op.add_column('Movies', sa.Column('release_year', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Movies', 'Actors', ['actor_id'], ['id'])
    op.drop_column('Movies', 'release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('release_date', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Movies', type_='foreignkey')
    op.drop_column('Movies', 'release_year')
    op.drop_column('Movies', 'actor_id')
    # ### end Alembic commands ###
